- name: Update the admin password on the junos device
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars:
    ansible_public_key: "{{ lookup('file', '/Users/USER/.ssh/id_rsa.pub') }}"
    ansible_python_interpreter: "/Users/USER/py-venv/ansible-2.10/bin/python3"
  vars_prompt:
  - name: USER
    prompt: Device user
    private: no
  - name: PASSWORD
    prompt: Device password
    private: yes
  tasks:
    - name: Build new admin password
      template:
        src: admin_password_update.conf.j2
        dest: ./admin_password_update.conf

    - name: Install config
      juniper_junos_config:
        host={{ junos_devices }}
        user={{ USER }}
        passwd={{ PASSWORD }}
        port=22
        timeout=500
        file=admin_password_update.conf
        comment="Committed by ansible {{ USER }} "
        load=merge
