- name: Update Junos root password
  hosts: juniper_devices
  gather_facts: no
  vars_prompt:
    - name: new_password
      prompt: "Enter new root password"
      private: yes
    - name: ansible_password
      prompt: "Enter ssh password"
      private: yes
  tasks:
    - name: Set new root password
      junipernetworks.junos.junos_system:
        host: "{{ inventory_hostname }}"
        port: 22
        user: root
        passwd: "{{ ansible_password }}"
        new_password: "{{ new_password }}"
      register: result
